### ISSUE TITLE
openai策略 节点问题

### ISSUE THREAD

**Issue by FFTU** [chinnsenn/ClashCustomRule#1]
你好，用你的配置，我发现proxies.list里面也有openai域名，那么就直接走节点选择的节点了，不会匹配到OpenAI策略的节点了，是不是应该把OpenAI策略放前面最好，或者把proxies.list里面相关Openai域名的删除？仅供参考，谢谢

**Comment by chinnsenn** [comment]
> 你好，用你的配置，我发现proxies.list里面也有openai域名，那么就直接走节点选择的节点了，不会匹配到OpenAI策略的节点了，是不是应该把OpenAI策略放前面最好，或者把proxies.list里面相关Openai域名的删除？仅供参考，谢谢

我确实没注意，我把 proxy.list 里的 openai 域名删除了。另外，如果再次碰到类似问题，你可以自建一个仓库，或者在 Github 的 gist 里建 list ，然后把策略组改成自己的新建的 list。毕竟每个人使用场景不一样，我这些分组也是自己一点点维护起来的，也不一定是最终形态。
